version: '3.8'

volumes:
  node_modules:

services:
  PaddleLabel-Frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: PaddleLabel-Frontend:latest
    container_name: 'PaddleLabel-Frontend'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true
    ports:
      - '8000:8000'
      - '3000:3000'
    volumes:
      - .:/usr/app
