# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate gh-pages

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: git config --global user.email "bot@github.com" && git config --global user.name "Action Bot"
      - run: npm i --global yarn
      - run: yarn
      - run: npm run build:gh-page
      - run: mv dist .. && git checkout . && git fetch && git checkout gh-page
      - run: rm -rf ./* && \cp -rf ../dist/* .
      - run: git add . && git commit -m "Auto update gh-page" && git push -f
